#!/bin/bash
#
# Copyright (c) 2005 Eric Engstrom
# See LICENSE for copying permissions and restrictions.
# Author:  Eric Engstrom (first(-DOT-)last(-AT-)g m a i l(-DOT-)c o m)
#
# See README.md for usage instructions and examples.
#
# Usage:
#    ssh-proxy [optional-args] [-p <http-proxy>[:<proxy-port>]] \
#                              [-h <ssh-hop-host>[:<hop-port>]] <host> <port>
# with optional args:
#   [-n <netcat>] - path of netcat/direct-connect program
#   [-s <ssh>]    - path of ssh client
#   [-t <tunnel>] - path of http-tunnel program
#   [-w <timout>] - timeout (seconds) to test connection to proxy server
#   [-S <regexp>] - regexp to pass to sed to modify destination hostname
#
# To Do:
#   * Should accept multiple hop or proxy and construct chained command
#   * sometimes re-times out over and over, queing multiple nc/ssh, but not sure why.
#   * evaulate use of `-X connect` option to nc for http proxy
#       (http://www.perkin.org.uk/posts/ssh-via-http-proxy-in-osx.html)
##

# set to "echo" to debug; use -v option to ssh to see output
DEBUG=

# defaults
ssh=ssh
agent="-A"         # forward agent
tunnel=corkscrew
timeout=8

# if "nc" not found, try "netcat"; check later
netcat=nc
if ! type -p ${netcat} >/dev/null 2>&1; then
  netcat="netcat"
fi

# parse args - can specify -n <netcat> and/or -t <tunnel>
while getopts "n:h:p:s:t:w:S:" OPT; do
  #echo "$OPT $OPTARG $OPTIND"
  case $OPT in
    h) arr=(${OPTARG//:/ }); hophost="${arr[0]}"; hopport=${arr[1]:+ -p ${arr[1]}} ;;
    p) arr=(${OPTARG//:/ }); proxyhost="${arr[0]}"; proxyport=${arr[1]} ;;
    n) netcat=$OPTARG ;;
    s) ssh=$OPTARG ;;
    t) tunnel=$OPTARG ;;
    w) timeout=$OPTARG ;;
    S) sedregexp=$OPTARG ;;
  esac
done
shift $(($OPTIND - 1))

# At this point $1 and $2 should be destination host and port, if specified.
if [ -n "${sedregexp}" ]; then
  desthost=$(echo "$1" | sed "${sedregexp}")
else
  desthost="$1"
fi
destport=${2:-22}  # default to port 22

#echo $desthost:$destport
#exit

# Check ability to use netcat now, after user specifies it
if ! type -p ${netcat} >/dev/null 2>&1; then
  echo "Cannot find netcat - failing..." 1>&2
  exit 1;
fi

# test connection to host directly; go direct if possible, else tunnel or hop
if ${netcat} -w ${timeout} -z ${desthost} ${destport} >/dev/null 2>&1; then
  $DEBUG exec ${netcat} ${desthost} ${destport}

# else, if proxy defined, then try that
elif [ -n "${proxyhost}" ]; then
  $DEBUG exec ${tunnel} ${proxyhost} ${proxyport} ${desthost} ${destport}

# else, if hop defined, then try that
elif [ -n "${hophost}" ]; then
  #echo "Connecting through ${hophost} to ${desthost}" 1>&2
  # This can recurse through your config file, which is OK sometimes,
  # but can also go badly if you try to hop through your to your hop host.
  # Break that cycle:
  if [ "${hophost}" == "${desthost}" ]; then
    echo "Trying to hop through ${hophost} to itself - failing..." 1>&2
    exit 1;
#  elif ping -q -t ${timeout} -no ${hophost}; then
#    echo "Cannot ping ${hophost} - failing..." 1>&2
#    exit 1;
  fi
  # Hop through hophost, using netcat to direct to real destination
  #$DEBUG exec ${ssh} ${agent} ${hophost} ${hopport} ${netcat} ${desthost} ${destport}
  # But, have had issues with above use of `exec` failing with error...
  #$DEBUG ${ssh} ${agent} ${hophost} ${hopport} ${netcat} ${desthost} ${destport}
  # Better yet, since OpenSSH 5.3 includes a -W option, which implements netcat-like directly.
  $DEBUG exec ${ssh} ${agent} ${hophost} ${hopport} -W ${desthost}:${destport}

# otherwise, we got SUEd...
else
  echo "No proxy or hop host specified - failing..." 1>&2
  exit 1;
fi

##
